import {
  Bell,
  Command,
  Search,
  PlusCircle,
  Flame,
  Activity,
  Circle,
  Plus,
  ChevronLeft,
  Globe,
  Dot,
  Home,
  Codesandbox,
  Github,
  User2,
  Blocks,
  Settings,
  CreditCard,
  FileText,
  LogOut,
  type LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  bell: Bell,
  command: Command,
  search: Search,
  addCircle: PlusCircle,
  add: Plus,
  flame: Flame,
  activity: Activity,
  circle: Circle,
  chevronLeft: ChevronLeft,
  globe: Globe,
  dot: Dot,
  home: Home,
  workspace: Codesandbox,
  github: Github,
  profile: User2,
  integration: Blocks,
  settings: Settings,
  billing: CreditCard,
  blogs: FileText,
  logout: LogOut,
};
